# Generated by Django 5.0.3 on 2024-07-19 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_post_category'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taggedpost',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag'),
        ),
    ]
