# Generated by Django 5.0.3 on 2024-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_taggedpost_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='placeholder.png', upload_to='featured_images/'),
        ),
    ]
